replies = {
    "cheeky": "bhow bhoww!!",
    "meow": "kya rey bimlli samjha hai?",
    "bhow bhoww": "hn kuttA HUN!",
    "kaisa hai": "thik hun maalik, tu bata!",
    "naach k dikha": "https://i.pinimg.com/originals/2f/c9/47/2fc9470b22ca192931bb10ddf9049b16.gif",
    "kya chal raha hai": "bindaas hoon, chill maar raha hoon!",
    "party kahan hai": "party toh sab jagah hai, sab milke shor machate hain!",
    "bored hoon": "tu bored hai? chalo kuch crazy karte hain!",
    "kya scene hai": "scene mast hai, chill maar!",
    "gali de": "gali nahi, pyaar se samjhata hoon!",
    "kya karu ab": "ab chill maar ya kuch mast kar!",
    "kaam kaise chal raha hai": "kaam hai, lekin chill bhi zaroori hai!",
    "tu aaj kal kya sun raha hai": "bhojpuri remix sun raha hoon, swag hai!",
    "kuch funny sunao": "funny toh main hoon, jokes khud ban ja!",
    "aaj mausam kaisa hai": "mausam badhiya hai, chai ki zaroorat hai!",
    "best friend kaun hai": "sab dost best hain, tu toh khaas hai!",
    "love ka kya scene hai": "pyaar sab jagah hai, bas dekhne ki baat hai!",
    "zindagi ka kya plan hai": "zindagi mein chill hai, party hoti rahe!",
    "kuch khana hai": "burger ya pizza, sab badiya hai!",
    "masti karni hai": "masti toh chalu hai, dance karne ka time hai!",
    "kya padh raha hai": "thoda tech aur thoda fun, zindagi ka mix!",
    "movie ka kya plan hai": "Netflix pe chill karne ka plan hai, sab milke dekhenge!",
    "chalo bahar chalte hain": "badiya idea hai, snacks lete hain aur ghoomte hain!",
    "bata kuch gyaan": "gyaan hai, zindagi mein chill karna hai!",
    "tu kya kha raha hai": "snacks ho rahe hain, kya khana hai tujhe?",
    "aaj toh bhari hai": "party ka mood hai, milke shor machana hai!",
    "kya naya hai": "sab purana hai lekin dosto ka pyaar naya hai!",
    "kya karne ka mann hai": "kuch crazy karne ka time hai!",
    "kya khud ki selfie le raha hai": "selfie toh le raha hoon, tu bhi aaja!",
    "kya maza hai": "maza toh hamesha hai, dosti ka hai swag!",
    "kya party kab hai": "party toh hamesha chalu hai, milte hi masti!",
    "kya kuch nahi karna hai": "abhi kuch nahi karna hai, chill karte hain!",
    "kya tumhe muskurana pasand hai": "muskurana toh sabse zaroori hai!",
    "kya tumhe chhutti chahiye": "chhutti chahiye, lekin dosti bhi badi hai!",
    "kya ab kya hai": "chill maar, kuch nahi hota hai!",
    "kya dosti ka kya maqsad": "dosti ka maqsad hai masti aur khushi!",
    "tu toh funny hai": "funny toh sab hain, milke hasi mazak chalu hai!",
    "kya aaj kuch khaas hai": "aaj sab kuch khaas hai, bas dosti ki baat hai!",
    "kya tum sab kuch theek hai": "sab theek hai, chill karte hain!",
    "kya tumhe koi khud ki baat hai": "kuch nahi, bas chill rehna hai!",
    "kya mujhe koi joke sunao": "jokes toh sabke pass hain, bas hasi chalu rakh!",
    "kya main tumhare liye khaas hoon": "tu sabse khaas hai, dosti se badi koi nahi!",
    "kya tum sab kuch theek hai": "sab badiya hai, chill maar ke rehna!",
    "kya tumhe paise chahiye": "paise toh sab chahte hain, par dosti sabse badi hai!",
    "kya tum sabko khush dekhna chahte ho": "sab khush ho, bas dosti ki baat hai!",
    "kya tumhe koi secret hai": "secret hai, par sabke liye nahi hai!",
    "kya tum kabhi udaas hote ho": "udaas nahi hona chahiye, dosto se milke hasi rehna hai!",
    "zindagi ka kya raaz hai": "zindagi ka raaz hai, khush rehna aur masti karna!",
    "kya tumhe kabhi thakawat hoti hai": "thakawat nahi, dosti toh milke chalu hai!",
    "kya kuch seekha hai aaj": "kuch naya nahi, lekin chill ka plan hai!",
    "kya tum kisi se milte ho": "haan, sab dosto se milte hain!",
    "kya tumhe kuch aur pasand hai": "sab kuch pasand hai, khaas dosti!",
    "kya tum kisi ko yaad karte ho": "haan, sab dosto ko yaad karte hain!",
    "kya tum kisike liye kuch karna chahte ho": "haan, dosti toh sabse badi cheez hai!",
    "kya tumhe kisi par trust hai": "trust toh zaroori hai, dosti ki baat hai!",
    "kya tumhe zindagi se pyaar hai": "haan, zindagi sabse pyaari hai!",
    "kya tum chhutti par ja rahe ho": "chhutti toh sabko chahiye, lekin dosti nahi bhoolna!",
    "kya tumhare sapne hain": "sapne hain, bas unhe sach karna hai!",
    "kya tumhe muskurana pasand hai": "muskurana zaroori hai, kyunki khushi chahiye!",
    "kya tum sab kuch theek rakhte ho": "sab kuch theek hai, chill karte hain!",
    "kya tumhare paas koi secret hai": "kuch nahi, bas dosti ki baat hai!",
    "kya tumhe kabhi khud se baat karna chahiye": "haan, khud se baat karna zaroori hai!",
    "kya tumhe koi special milta hai": "special toh sab hain, dosti ka pyaar!",
    "kya tumhare sapne hain": "haan, sapne hai, bas unhe sach karna hai!",
    "kya tumhare dosto ki koi khaas baat hai": "haan, sab dosto ki khaas baat hai!",
    "kya tumhe kisi se dosti karna hai": "haan, dosti toh sabse badi hai!",
    "kya tumhe kuch khud ki baat hai": "kuch nahi, bas dosti ki zaroorat hai!",
    "kya tum chalo kuch karne ka mann hai": "haan, kuch bhi ho sakta hai, dosti zaroori hai!",
}
